### ISSUE TITLE
Development planning, Milestone 2

### ISSUE THREAD

**Issue by mike-lischke** [mike-lischke/ANTLRng#9]
Here's the list of planned tasks for this milestone, now that the new TypeScript runtime (antlr4ng) is working well.

- [x] Convert [ST4](https://github.com/antlr/stringtemplate4) to TypeScript ([stringtemplate4ts](https://github.com/mike-lischke/stringtemplate4ts))
- [x] ANTLR4 runtime tests in TypeScript, currently being ported from the Java runtime tests and stored in this repo. They will move to the TS runtime repo once they are all finished.
- [x] Work out the fundamental design of runtime testing, where each runtime author is responsible for his own tests. This is a major change from the current situation, where the tool author is responsible for all runtimes.
- [x] antlr4ng completed (100% coverage of the Java runtime).

**Comment by mike-lischke** [comment]
Converting StringTemplate 4 to TypeScript is a real pain and annoying side task, as I actually want to get rid of it. But migrating to a new template approach at the same time when converting ANTLR4 is probably too risky and might be more time consuming than just biting the bullet and convert ST4 first. Maybe someone can benefit from this at least.

**Comment by mike-lischke** [comment]
Coverage of the Java runtime is nearly 100% complete ([tracked in an own branch](https://github.com/mike-lischke/antlr4ng/tree/complete)), except for Java specific classes.
